sudo: required
dist: trusty
language: python

before_script:
  - export PATH=$HOME/.local/bin:$PATH
  - sudo pip install google-api-python-client pyyaml python-dateutil NewlineJSON pytz yattag

script:
  - ./test_all
