language: python

sudo: required

services: docker

cache:
  directories:
  - ~/.cache/pip

python:
- 2.7

install:
  - docker volume create --name=gcp
  - docker-compose build

script:
  - docker-comoose --version
  - docker-compose run test
