FROM gcr.io/world-fishing-827/github.com/globalfishingwatch/gfw-pipeline:latest-python3.8

# Setup local application dependencies
COPY ./requirements.txt ./
RUN pip install -r requirements.txt

# Temporary. TODO: Use a local test docker image with extra dependencies.
COPY ./requirements/test.txt ./
RUN pip install -r test.txt

# Temporary. TODO: Use a local dev docker image with extra dependencies.
COPY ./requirements/dev.txt ./
RUN pip install -r dev.txt

# Setup local packages
COPY . /opt/project
RUN pip install -e .

# Setup the entrypoint for quickly executing the pipelines
ENTRYPOINT ["./main.py"]
