services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile-scheduler
    image: gfw/pipe-encounters
    volumes:
      - ".:/opt/project"
      - "gcp:/root/.config/"
  gcloud:
    image: gfw/pipe-segment
    build:
      context: .
      dockerfile: Dockerfile-scheduler
    entrypoint: gcloud
    volumes:
      - "gcp:/root/.config/"

volumes:
  gcp:
    external: True
