version: '2'
services:
  pipe_encounters:
    build:
      context: .
      dockerfile: Dockerfile-scheduler
    image: gfw/pipe-encounters
    volumes:
      - ".:/opt/project"
      - "gcp:/root/.config/"

  create_raw_encounters:
    build:
      context: .
      dockerfile: Dockerfile-scheduler
    image: gfw/pipe-encounters
    volumes:
      - ".:/opt/project"
      - "gcp:/root/.config/"
    entrypoint: ["python", "-m", "pipeline.create_raw_encounters"]

  merge_encounters:
    build:
      context: .
      dockerfile: Dockerfile-scheduler
    image: gfw/pipe-encounters
    volumes:
      - ".:/opt/project"
      - "gcp:/root/.config/"
    entrypoint: ["python", "-m", "pipeline.merge_encounters"]

volumes:
  gcp:
    external: True

