version: '2'
services:
  create_raw_encounters:
    entrypoint: ["python", "-m", "pipeline.create_raw_encounters"]  
    image: gfw/pipe-encounters
    build: .
    volumes:
      - ".:/opt/project"
      - "gcp:/root/.config/"
  merge_encounters:
    entrypoint: ["python", "-m", "pipeline.merge_encounters"]  
    image: gfw/pipe-encounters
    build: .
    volumes:
      - ".:/opt/project"
      - "gcp:/root/.config/"
  test:
    entrypoint: ["py.test"]  
    image: gfw/pipe-encounters
    build: .
    volumes:
      - ".:/opt/project"
      - "gcp:/root/.config/"
volumes:
  gcp:
    external: True

